kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-ebs-static

spec:
  capacity:
    storage: 25Gi
  accessModes:
  -  ReadWriteOnce
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0163db25c0507d56e

