apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prod
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 25Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-026d848a0cbc57423
 