kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-ebs-claim

spec:
  volumeName: pv-ebs-static
  resources:
    requests:
      storage: "25Gi"
  accessModes:
    - ReadWriteOnce
  storageClassName: ""

---
kind: Pod
apiVersion: v1
metadata:
  name: pod-static
  labels:
    demo: "static-pv"
spec:
  containers:
  - name: static-nginx
    image: nginx
    volumeMounts:
    - name: pv-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: pv-storage
    persistentVolumeClaim:
      claimName: pvc-ebs-claim

---
kind: Service
apiVersion: v1
metadata:
  name: static-lb

spec:
  type: LoadBalancer
  selector:
    demo: "static-pv"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007


    