kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-ebs-claim

spec:
  volumeName: pv-ebs-static
  resources:
    requests:
      storage: "25Gi"
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  

    