kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-ebs-claim

spec:
    storageClassName: " "
    accessModes:
      - ReadWriteOnce
    mounts:
      mountPath: /usr/share/nginx/html
    resources:
      requests:
        storage: "25Gi"
    volumeName:
      name: pv-ebs-static