kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
  name: ebs-dynamic-pvc
spec:
  storageClassName: "ebs-sc"
  resources:
    requests:
      storage: "29Gi"
  accessModes:
    - ReadWriteOnce

---
kind: Pod
apiVersion: v1
metadata:
  name: dynamic-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        name: Persistent-Storage
        mount: /usr/share/nginx/html
  volumes:
    - name: Persistent-Storage
      persistentVolumeClaim:
        claimName: "ebs-dynamic-pvc"
