kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-static-pvc

spec:
  accessModes:
    -ReadWriteOnce
  storageClassName: ""
  volumeName: "pv-efs-static"
  resources:
    requests:
      storage: "5Gi"