kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-dynamic-sc
provisioner: efs.csi.aws.com
parameters:
  provisioiningMode: efs-ap
  filesystemId: fs-07c58093192b215a1
  directoryPerms: "700"
  basePath: "/expense"