kind: Pod
apiVersion: v1
metadata:
  name: annotations
  annotations:
    build_url: "https://hellow.jason.txt"
    image_url: "https:docker.com/api"
spec:
  containers:
  - name: nginx
    image: nginx

---

apiVersion: v1
kind: Pod
metadata:
  name: annotations-demo
  annotations:
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80