kind: Pod
apiVersion: V1
metadata:
  name: annotations
  annotation:
    build_url: https://hellow.jason.txt
    image_url: https:docker.com/api
  spec:
    - containers:
      name: nginx
      image: nginx