kind: Pod
apiVersion: v1
metadata:
  name: resourcelimit
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "250Mi"
        memory: "100Mi"
      limits:
        cpu: "300Mi"
        memory: "150Mi"
  - name: log-aggregator
    image: images.my-company.example/log-aggreagator:v6
    resources:
      requests:
        cpu: "150Mi"
        memory: "100Mi"
      limits:
        cpu: "150Mi"
        memory: "100Mi"

---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: app
    image: images.my-company.example/app:v4
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: log-aggregator2
    image: images.my-company.example/log-aggregator:v6
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"