kind: Namespace
apiVersion: v1
metadata:
  name: prod


---
kind: ReplicaSet
apiVersion: apps/v1
metadata: 
   name: repset
   namespace: prod
   labels:
      course: devops
      trainer: Dhanunjaya
      hours: hundred
   
spec:
  replicas: 3
  selector:
    matchLabels:
      course: devops
      trainer: Dhanunjaya
      hours: hundred
  template:
    metadata:
      labels:
        course: devops
        trainer: Dhanunjaya
        hours: hundred
      annotaions:
        buildUrl: "https://vrushali.online.com"

    spec:
      containers:
        - name: nginx
          image: nginx
