kind: Secret
apiVersion: v1
metadata:
  name: secret
  namespace: prod
type: Opaque
data:
  username: "ZGhhbnVuamF5YQ=="
  password: "dnJ1c2hhbGlAOTg0NTYjc2h1Ymhhc2hpbmk="


---
kind: Pod
apiVersion: v1
metadata:
  name: sercretpod
  namespace: prod
spec: 
  containers:
    - name: nginx
      imaage: nginx
      envFrom:
      - secret:
        name: secret
          

