kind: Secrets
apiVersion: apps/v1
metadata:
  name: secret
  namespace: prod
type: opaque
data:
  username: "ZGhhbnVuamF5YQ=="
  password: "dnJ1c2hhbGlAOTg0NTYjc2h1Ymhhc2hpbmk="


---
kind: Pod
apiVersion: v1
metadata:
  name: sercretPod
  namespace: prod
spec: 
  containers:
    - name: nginx
      imaage: nginx
      env:
        -secretMapRef:
          name: secret

