kind: Service
apiVersion: v1
metadata:
  name: internal-service
  namespace: prod
spec:
  selectors:
    course: devops
    trainer: dhanunjaya
    application: backend
    version: clusterIP
  ports:
  - name: name-of-service-port
    protocol: tcp
    port: 80
    targetPort: 8080


---
kind: Pod
apiVersion: v1
metadata:
  name: servicepod
  namespace: prod
  labels:
    course: devops
    trainer: dhanunjaya
    application: backend
    version: clusterIP
spec:
  containers:
  - name: nginx
    image: nginx