kind: Service
apiVersion: v1
metadata:
  name: service-lb
  namespace: prod
spec:
  type: LoadBalancer
  selector:
    course: devops
    trainer: dhanunjaya
    application: backend
    version: clusterIP
    demo: lb
  ports:
  - name: name-of-service-port
    protocol: "TCP"
    port: 80
    targetPort: 8080
    nodePort: 30010


---
kind: Pod
apiVersion: v1
metadata:
  name: servicepod-lb
  namespace: prod
  labels:
    course: devops
    trainer: dhanunjaya
    application: backend
    version: clusterIP
    demo: lb
spec:
  containers:
  - name: nginx
    image: nginx