kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-role
  namespace: expense
rules:
- apiGroup: [" "]
  resources: ["*"]
  verbs: ["get","watch","list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io
metadata:
  name: sa-rb
  namespace: expense
subjects:
- kind: ServiceAccount
  name: expense-sa
  namespace: expense
roleRef:
  kind: Role
  name: sa-role
  apiGroup: rbac.authorization.k8s.io

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: expense-sa-pod
  namespace: expense
spec:
  serviceAccount: expense-sa


---
apiVersion: v1
kind: Pod
metadata:
  name: sa-pod
  namespace: expense
spec:
  serviceAccount: expense-mysql-secret
  initContainers:
  - name: aws-cli
    image: amazonlinux:2023
    # command: ['sh', '-c', 'aws secretsmanager get-secret-value --secret-id expense/mysql/creds --query SecretString --output text > /secrets/.env ']
    command: ['sh', '-c']
    args:
    - |
      yum install -y unzip awscli
      aws secretsmanager get-secret-value --secret-id expense/mysql/creds --query SecretString --output text > /secrets/.env
    volumeMounts:
    - mountPath: /secrets
      name: secret-volume
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /secrets
      name: secret-volume
  volumes:
  - name: secret-volume
    emptyDir: {}
  

